- name: Install Docker
  apt:
    name:
      - docker-ce
      - docker-ce-cli
      - containerd.io
      - docker-compose
      - python3-docker
    state: present
    update_cache: yes

- name: Create directories
  file:
    path: /opt/jackett
    state: directory
    mode: '0755'

- name: Copy docker-compose
  copy:
    src: docker-compose.yml
    dest: /opt/jackett/docker-compose.yml

- name: Stop and remove existing docker-compose containers
  command: docker-compose -f /opt/jackett/docker-compose.yml down
  register: compose_down
  failed_when: false

- name: Run docker-compose
  command: docker-compose -f /opt/jackett/docker-compose.yml up -d
