[mc]
mc-server ansible_host=mc-server.local 

[samba]
samba-server ansible_host=samba-server.local 

[all:vars]
ansible_user=root
# ansible_password=techisawesome # CHANGE THIS TO YOUR ACTUAL ROOT PASSWORD
