#cloud-config
chpasswd:
  list: |
    root:techisawesome
    tech:techisawesome
  expire: false
ssh_pwauth: true

packages:
  - qemu-guest-agent

runcmd:
  - systemctl enable qemu-guest-agent
  - systemctl start qemu-guest-agent