{ config, modulesPath, pkgs, lib, ... }:
{
  imports = [ (modulesPath + "/virtualisation/proxmox-lxc.nix") ];
  nix.settings = { sandbox = false; };  
  proxmoxLXC = {
    manageNetwork = false;
  };
  services.fstrim.enable = false; # Let Proxmox host handle fstrim
  services.openssh = {
    enable = true;
    openFirewall = true;
    settings = {
        PermitRootLogin = "yes";
        PasswordAuthentication = true;
        PermitEmptyPasswords = "yes";
    };
  };

  # Make systemd-resolved send .local domain queries to the DHCP-provided DNS server,
  # instead of trying to resolve them via mDNS.
  # We do this by injecting Domains=~local into the networkd config generated by Proxmox.
  environment.etc."systemd/network/eth0.network.d/local-domain.conf".text = ''
    [Network]
    Domains=~local ~.
  '';
}
