---
- name: Install Samba
  apt:
    update_cache: yes
    name:
      - samba
      - smbclient
      - cifs-utils
    state: present

- name: Create shared directory
  file:
    path: /srv/samba/share
    state: directory
    mode: '0777'
    owner: nobody
    group: nogroup

- name: Configure Samba share
  blockinfile:
    path: /etc/samba/smb.conf
    block: |
      [share]
      path = /srv/samba/share
      browseable = yes
      read only = no
      guest ok = yes
      create mask = 0777
      directory mask = 0777
      force user = nobody
      strict locking = no
      oplocks = yes
      wide links = yes
      follow symlinks = yes
      unix extensions = no
      acl allow execute always = yes
    marker: "# {mark} ANSIBLE MANAGED BLOCK share"
  notify: restart samba

- name: Ensure Samba service is running and enabled on boot
  service:
    name: smbd
    state: started
    enabled: yes
